env:
  es2021: true

extends:
  - standard-with-typescript

parserOptions:
  ecmaVersion: latest
  project:
    - './tsconfig.eslint.json'

rules:
  '@typescript-eslint/indent':
    - 'error'
    - '4'
  '@typescript-eslint/space-before-function-paren': 'off'

plugins:
  - eslint-plugin-prettier
